name: Publish NuGet Package

on:
  push:
    tags:
      - 'v.1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Empacotar NuGet
        run: dotnet pack --configuration Release -p:PackageVersion=${{ github.ref_name }} -o ./nupkg

      - name: Publicar no NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
