name: Publish NuGet Package

on:
  push:
    branches:
      - main
    tags:
      - 'v.1.0.0'
  pull_request:
    types: [ closed ]
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Instalar GitVersion
        uses: GitTools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: '5.x'

      - name: Rodar GitVersion
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v0.9.14
        
      - name: Restaurar dependências
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

#      - name: Empacotar NuGet
#        run: dotnet pack --configuration Release -p:PackageVersion=${{ steps.gitversion.outputs.nuGetVersionV2 }} -o ./nupkg
      
      - name: Empacotar NuGet
        run: dotnet pack --configuration Release -p:PackageVersion=1.0.1 -o ./nupkg
        
      - name: Publicar no NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
